// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import DeviceCodeConfirmation from '@auth0/auth0-acul-js/device-code-confirmation';

const DeviceCodeConfirmationContext = createContext<DeviceCodeConfirmation | null>(null);

export function useDeviceCodeConfirmation(): DeviceCodeConfirmation {
  return useMemo(() => new DeviceCodeConfirmation(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useDeviceCodeConfirmation();
  return <DeviceCodeConfirmationContext.Provider value={screen}>{children}</DeviceCodeConfirmationContext.Provider>;
};

export function useAculContext(): DeviceCodeConfirmation {
  const screen = useContext(DeviceCodeConfirmationContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/device-code-confirmation';
