// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import DeviceCodeActivationAllowed from '@auth0/auth0-acul-js/device-code-activation-allowed';

const DeviceCodeActivationAllowedContext = createContext<DeviceCodeActivationAllowed | null>(null);

export function useDeviceCodeActivationAllowed(): DeviceCodeActivationAllowed {
  return useMemo(() => new DeviceCodeActivationAllowed(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useDeviceCodeActivationAllowed();
  return <DeviceCodeActivationAllowedContext.Provider value={screen}>{children}</DeviceCodeActivationAllowedContext.Provider>;
};

export function useAculContext(): DeviceCodeActivationAllowed {
  const screen = useContext(DeviceCodeActivationAllowedContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/device-code-activation-allowed';
