// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import DeviceCodeActivation from '@auth0/auth0-acul-js/device-code-activation';

const DeviceCodeActivationContext = createContext<DeviceCodeActivation | null>(null);

export function useDeviceCodeActivation(): DeviceCodeActivation {
  return useMemo(() => new DeviceCodeActivation(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useDeviceCodeActivation();
  return <DeviceCodeActivationContext.Provider value={screen}>{children}</DeviceCodeActivationContext.Provider>;
};

export function useAculContext(): DeviceCodeActivation {
  const screen = useContext(DeviceCodeActivationContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/device-code-activation';
