// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import DeviceCodeActivationDenied from '@auth0/auth0-acul-js/device-code-activation-denied';

const DeviceCodeActivationDeniedContext = createContext<DeviceCodeActivationDenied | null>(null);

export function useDeviceCodeActivationDenied(): DeviceCodeActivationDenied {
  return useMemo(() => new DeviceCodeActivationDenied(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useDeviceCodeActivationDenied();
  return <DeviceCodeActivationDeniedContext.Provider value={screen}>{children}</DeviceCodeActivationDeniedContext.Provider>;
};

export function useAculContext(): DeviceCodeActivationDenied {
  const screen = useContext(DeviceCodeActivationDeniedContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/device-code-activation-denied';
