// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import Login from '@auth0/auth0-acul-js/login';

const LoginContext = createContext<Login | null>(null);

export function useLogin(): Login {
  return useMemo(() => new Login(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useLogin();
  return <LoginContext.Provider value={screen}>{children}</LoginContext.Provider>;
};

export function useAculContext(): Login {
  const screen = useContext(LoginContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/login';
