// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import LoginPasswordlessEmailCode from '@auth0/auth0-acul-js/login-passwordless-email-code';

const LoginPasswordlessEmailCodeContext = createContext<LoginPasswordlessEmailCode | null>(null);

export function useLoginPasswordlessEmailCode(): LoginPasswordlessEmailCode {
  return useMemo(() => new LoginPasswordlessEmailCode(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useLoginPasswordlessEmailCode();
  return <LoginPasswordlessEmailCodeContext.Provider value={screen}>{children}</LoginPasswordlessEmailCodeContext.Provider>;
};

export function useAculContext(): LoginPasswordlessEmailCode {
  const screen = useContext(LoginPasswordlessEmailCodeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/login-passwordless-email-code';
