// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import LoginPassword from '@auth0/auth0-acul-js/login-password';

const LoginPasswordContext = createContext<LoginPassword | null>(null);

export function useLoginPassword(): LoginPassword {
  return useMemo(() => new LoginPassword(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useLoginPassword();
  return <LoginPasswordContext.Provider value={screen}>{children}</LoginPasswordContext.Provider>;
};

export function useAculContext(): LoginPassword {
  const screen = useContext(LoginPasswordContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/login-password';
