// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaRecoveryCodeChallenge from '@auth0/auth0-acul-js/mfa-recovery-code-challenge';

const MfaRecoveryCodeChallengeContext = createContext<MfaRecoveryCodeChallenge | null>(null);

export function useMfaRecoveryCodeChallenge(): MfaRecoveryCodeChallenge {
  return useMemo(() => new MfaRecoveryCodeChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaRecoveryCodeChallenge();
  return <MfaRecoveryCodeChallengeContext.Provider value={screen}>{children}</MfaRecoveryCodeChallengeContext.Provider>;
};

export function useAculContext(): MfaRecoveryCodeChallenge {
  const screen = useContext(MfaRecoveryCodeChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-recovery-code-challenge';
