// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaVoiceEnrollment from '@auth0/auth0-acul-js/mfa-voice-enrollment';

const MfaVoiceEnrollmentContext = createContext<MfaVoiceEnrollment | null>(null);

export function useMfaVoiceEnrollment(): MfaVoiceEnrollment {
  return useMemo(() => new MfaVoiceEnrollment(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaVoiceEnrollment();
  return <MfaVoiceEnrollmentContext.Provider value={screen}>{children}</MfaVoiceEnrollmentContext.Provider>;
};

export function useAculContext(): MfaVoiceEnrollment {
  const screen = useContext(MfaVoiceEnrollmentContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-voice-enrollment';
