// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaEmailList from '@auth0/auth0-acul-js/mfa-email-list';

const MfaEmailListContext = createContext<MfaEmailList | null>(null);

export function useMfaEmailList(): MfaEmailList {
  return useMemo(() => new MfaEmailList(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaEmailList();
  return <MfaEmailListContext.Provider value={screen}>{children}</MfaEmailListContext.Provider>;
};

export function useAculContext(): MfaEmailList {
  const screen = useContext(MfaEmailListContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-email-list';
