// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaVoiceChallenge from '@auth0/auth0-acul-js/mfa-voice-challenge';

const MfaVoiceChallengeContext = createContext<MfaVoiceChallenge | null>(null);

export function useMfaVoiceChallenge(): MfaVoiceChallenge {
  return useMemo(() => new MfaVoiceChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaVoiceChallenge();
  return <MfaVoiceChallengeContext.Provider value={screen}>{children}</MfaVoiceChallengeContext.Provider>;
};

export function useAculContext(): MfaVoiceChallenge {
  const screen = useContext(MfaVoiceChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-voice-challenge';
