// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaPhoneEnrollment from '@auth0/auth0-acul-js/mfa-phone-enrollment';

const MfaPhoneEnrollmentContext = createContext<MfaPhoneEnrollment | null>(null);

export function useMfaPhoneEnrollment(): MfaPhoneEnrollment {
  return useMemo(() => new MfaPhoneEnrollment(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaPhoneEnrollment();
  return <MfaPhoneEnrollmentContext.Provider value={screen}>{children}</MfaPhoneEnrollmentContext.Provider>;
};

export function useAculContext(): MfaPhoneEnrollment {
  const screen = useContext(MfaPhoneEnrollmentContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-phone-enrollment';
