// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaPhoneChallenge from '@auth0/auth0-acul-js/mfa-phone-challenge';

const MfaPhoneChallengeContext = createContext<MfaPhoneChallenge | null>(null);

export function useMfaPhoneChallenge(): MfaPhoneChallenge {
  return useMemo(() => new MfaPhoneChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaPhoneChallenge();
  return <MfaPhoneChallengeContext.Provider value={screen}>{children}</MfaPhoneChallengeContext.Provider>;
};

export function useAculContext(): MfaPhoneChallenge {
  const screen = useContext(MfaPhoneChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-phone-challenge';
