// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaOtpEnrollmentCode from '@auth0/auth0-acul-js/mfa-otp-enrollment-code';

const MfaOtpEnrollmentCodeContext = createContext<MfaOtpEnrollmentCode | null>(null);

export function useMfaOtpEnrollmentCode(): MfaOtpEnrollmentCode {
  return useMemo(() => new MfaOtpEnrollmentCode(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaOtpEnrollmentCode();
  return <MfaOtpEnrollmentCodeContext.Provider value={screen}>{children}</MfaOtpEnrollmentCodeContext.Provider>;
};

export function useAculContext(): MfaOtpEnrollmentCode {
  const screen = useContext(MfaOtpEnrollmentCodeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-otp-enrollment-code';
