// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import MfaRecoveryCodeEnrollment from '@auth0/auth0-acul-js/mfa-recovery-code-enrollment';

const MfaRecoveryCodeEnrollmentContext = createContext<MfaRecoveryCodeEnrollment | null>(null);

export function useMfaRecoveryCodeEnrollment(): MfaRecoveryCodeEnrollment {
  return useMemo(() => new MfaRecoveryCodeEnrollment(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useMfaRecoveryCodeEnrollment();
  return <MfaRecoveryCodeEnrollmentContext.Provider value={screen}>{children}</MfaRecoveryCodeEnrollmentContext.Provider>;
};

export function useAculContext(): MfaRecoveryCodeEnrollment {
  const screen = useContext(MfaRecoveryCodeEnrollmentContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/mfa-recovery-code-enrollment';
