// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import OrganizationSelection from '@auth0/auth0-acul-js/organization-selection';

const OrganizationSelectionContext = createContext<OrganizationSelection | null>(null);

export function useOrganizationSelection(): OrganizationSelection {
  return useMemo(() => new OrganizationSelection(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useOrganizationSelection();
  return <OrganizationSelectionContext.Provider value={screen}>{children}</OrganizationSelectionContext.Provider>;
};

export function useAculContext(): OrganizationSelection {
  const screen = useContext(OrganizationSelectionContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/organization-selection';
