// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import PhoneIdentifierChallenge from '@auth0/auth0-acul-js/phone-identifier-challenge';

const PhoneIdentifierChallengeContext = createContext<PhoneIdentifierChallenge | null>(null);

export function usePhoneIdentifierChallenge(): PhoneIdentifierChallenge {
  return useMemo(() => new PhoneIdentifierChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = usePhoneIdentifierChallenge();
  return <PhoneIdentifierChallengeContext.Provider value={screen}>{children}</PhoneIdentifierChallengeContext.Provider>;
};

export function useAculContext(): PhoneIdentifierChallenge {
  const screen = useContext(PhoneIdentifierChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/phone-identifier-challenge';
