// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import RedeemTicket from '@auth0/auth0-acul-js/redeem-ticket';

const RedeemTicketContext = createContext<RedeemTicket | null>(null);

export function useRedeemTicket(): RedeemTicket {
  return useMemo(() => new RedeemTicket(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useRedeemTicket();
  return <RedeemTicketContext.Provider value={screen}>{children}</RedeemTicketContext.Provider>;
};

export function useAculContext(): RedeemTicket {
  const screen = useContext(RedeemTicketContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/redeem-ticket';
