// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import ResetPassword from '@auth0/auth0-acul-js/reset-password';

const ResetPasswordContext = createContext<ResetPassword | null>(null);

export function useResetPassword(): ResetPassword {
  return useMemo(() => new ResetPassword(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useResetPassword();
  return <ResetPasswordContext.Provider value={screen}>{children}</ResetPasswordContext.Provider>;
};

export function useAculContext(): ResetPassword {
  const screen = useContext(ResetPasswordContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/reset-password';
