// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import ResetPasswordMfaPhoneChallenge from '@auth0/auth0-acul-js/reset-password-mfa-phone-challenge';

const ResetPasswordMfaPhoneChallengeContext = createContext<ResetPasswordMfaPhoneChallenge | null>(null);

export function useResetPasswordMfaPhoneChallenge(): ResetPasswordMfaPhoneChallenge {
  return useMemo(() => new ResetPasswordMfaPhoneChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useResetPasswordMfaPhoneChallenge();
  return <ResetPasswordMfaPhoneChallengeContext.Provider value={screen}>{children}</ResetPasswordMfaPhoneChallengeContext.Provider>;
};

export function useAculContext(): ResetPasswordMfaPhoneChallenge {
  const screen = useContext(ResetPasswordMfaPhoneChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/reset-password-mfa-phone-challenge';
