// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import ResetPasswordMfaVoiceChallenge from '@auth0/auth0-acul-js/reset-password-mfa-voice-challenge';

const ResetPasswordMfaVoiceChallengeContext = createContext<ResetPasswordMfaVoiceChallenge | null>(null);

export function useResetPasswordMfaVoiceChallenge(): ResetPasswordMfaVoiceChallenge {
  return useMemo(() => new ResetPasswordMfaVoiceChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useResetPasswordMfaVoiceChallenge();
  return <ResetPasswordMfaVoiceChallengeContext.Provider value={screen}>{children}</ResetPasswordMfaVoiceChallengeContext.Provider>;
};

export function useAculContext(): ResetPasswordMfaVoiceChallenge {
  const screen = useContext(ResetPasswordMfaVoiceChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/reset-password-mfa-voice-challenge';
