// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import ResetPasswordMfaRecoveryCodeChallenge from '@auth0/auth0-acul-js/reset-password-mfa-recovery-code-challenge';

const ResetPasswordMfaRecoveryCodeChallengeContext = createContext<ResetPasswordMfaRecoveryCodeChallenge | null>(null);

export function useResetPasswordMfaRecoveryCodeChallenge(): ResetPasswordMfaRecoveryCodeChallenge {
  return useMemo(() => new ResetPasswordMfaRecoveryCodeChallenge(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useResetPasswordMfaRecoveryCodeChallenge();
  return <ResetPasswordMfaRecoveryCodeChallengeContext.Provider value={screen}>{children}</ResetPasswordMfaRecoveryCodeChallengeContext.Provider>;
};

export function useAculContext(): ResetPasswordMfaRecoveryCodeChallenge {
  const screen = useContext(ResetPasswordMfaRecoveryCodeChallengeContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/reset-password-mfa-recovery-code-challenge';
