// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import SignupId from '@auth0/auth0-acul-js/signup-id';

const SignupIdContext = createContext<SignupId | null>(null);

export function useSignupId(): SignupId {
  return useMemo(() => new SignupId(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useSignupId();
  return <SignupIdContext.Provider value={screen}>{children}</SignupIdContext.Provider>;
};

export function useAculContext(): SignupId {
  const screen = useContext(SignupIdContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/signup-id';
