// AUTO-GENERATED FILE - DO NOT EDIT
// This file was generated by scripts/generate-react-sdk.ts

import React, { createContext, useContext, useMemo } from 'react';
import Signup from '@auth0/auth0-acul-js/signup';

const SignupContext = createContext<Signup | null>(null);

export function useSignup(): Signup {
  return useMemo(() => new Signup(), []);
}

export const Auth0AculProvider = ({ children }: { children: React.ReactNode }) => {
  const screen = useSignup();
  return <SignupContext.Provider value={screen}>{children}</SignupContext.Provider>;
};

export function useAculContext(): Signup {
  const screen = useContext(SignupContext);
  if (!screen) {
    throw new Error('useAculContext must be used within an <Auth0AculProvider>');
  }
  return screen;
}

export type * from '@auth0/auth0-acul-js/signup';
