export const FormActions = {
  DEFAULT: 'default' as const,
  BACK: 'back-action' as const,
  PICK_AUTHENTICATOR: 'pick-authenticator' as const,
  PICK_SMS: 'pick-sms' as const,
  PICK_EMAIL: 'pick-email' as const,
  PICK_COUNTRY_CODE: 'pick-country-code' as const,
  RESEND_CODE: 'resend-code' as const,
  RESEND: 'resend' as const,
  CONTINUE: 'continue' as const,
  TOGGLE_VIEW: 'toggle-view' as const,
  ENTER_OTP_CODE: 'enter-otp-code' as const,
  SWITCH_TO_VOICE: 'switch-to-voice' as const,
  SWITCH_TO_TEXT: 'switch-to-text' as const,
  ABORT_PASSKEY_ENROLLMENT: 'abort-passkey-enrollment' as const,
  BACK_TO_LOGIN: 'back-to-login' as const,
  ACCEPT: 'accept' as const,
  DENY: 'deny' as const,
  ENROLL: 'enroll' as const,
  RESEND_EMAIL: 'resend-email-action' as const,
  PICK_PHONE: 'pick-phone' as const,
  SWITCH_TO_SMS: 'switch-to-sms' as const,
  CONFIRM: 'confirm' as const,
  CANCEL: 'cancel' as const,
  // actions for MFA WebAuthn Platform Enrollment
  SHOW_ERROR_ACTION_PREFIX: 'showError::' as const,
  SNOOZE_ENROLLMENT: 'snooze-enrollment' as const,
  REFUSE_ADD_DEVICE: 'refuse-add-device' as const,
  // actions for MFA WebAuthn Error
  TRY_AGAIN: 'tryagain' as const,
  USE_PASSWORD: 'use-password' as const,
  CHANGE_LANGUAGE: 'change-language' as const,
} as const;
