// Generated by ts-to-zod
import { z } from "zod";

export const SignupOptionsSchema = z
  .record(z.union([z.string(), z.number(), z.boolean(), z.undefined()]))
  .and(
    z.object({
      email: z.string().email({ message: "email is required" }),
      username: z.string().min(1, { message: "Username is required" }),
      phone_number: z.string().optional(),
      password: z.string().min(1, { message: "Password is required" }),
      captcha: z.string().optional(),
    }),
  );


