name: Publish release to npm

inputs:
  node-version:
    required: true
  npm-token:
    required: true
  version:
    required: true
  require-build:
    required: true
  package:
    required: true
  release-directory:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        token: ${{ inputs.npm-token }}

    - name: Install dependencies
      shell: bash
      run: npm ci --workspaces --include-workspace-root

    - name: Build package
      if: inputs.require-build == 'true'
      shell: bash
      working-directory: packages/${{ inputs.package }}
      run: npm run build

    - name: Publish release to NPM
      working-directory: packages/${{ inputs.release-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        VERSION: ${{ inputs.version }}
      run: |
        if [[ "${VERSION}" == *"beta"* ]]; then
          TAG="beta"
        elif [[ "${VERSION}" == *"alpha"* ]]; then
          TAG="alpha"
        else
          TAG="latest"
        fi
        npm publish --provenance --access public --tag $TAG
      shell: bash

