# .github/workflows/security.yml
name: Security

on:
  schedule:
    - cron: '0 0 * * *' # daily
  push:
    branches: [main]
  pull_request:

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk for all packages
        run: |
          for dir in packages/*; do
            echo "Scanning $dir"
            snyk test --all-projects --file=$dir/package.json || true
          done

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --exclude node_modules
